spring.application.name=SoundFork

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/soundfork}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.flyway.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.upload-dir=${UPLOAD_DIR:uploads}
app.jwt.secret=${JWT_SECRET:soundfork-secret-key-change-in-production}

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8081}
notification.topic=notification.topic
spring.cache.type=${CACHE_TYPE:redis}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
